export const GAME_STATES = {
    BOOT: "BOOT",
    MENU: "MENU",
    PLAYING: "PLAYING",
    PAUSED: "PAUSED",
    GAMEOVER: "GAMEOVER",
    SHOP: "SHOP",
    INVENTORY: "INVENTORY"
};

export const RENDER_CONFIG = {
    FOV: 60,
    NEAR: 0.1,
    FAR: 2000,
    BOUNDS_X: 450,
    BOUNDS_Y: 300,
    PLAYER_Z: 100
};

export const ENTITY_TYPES = {
    PLAYER: "PLAYER",
    ENEMY_DRONE: "ENEMY_DRONE",
    ENEMY_BOSS: "ENEMY_BOSS",
    BULLET_PLAYER: "BULLET_PLAYER",
    BULLET_ENEMY: "BULLET_ENEMY"
};

export const WEAPON_TYPES = {
    STANDARD: "STANDARD",
    DUAL: "DUAL",
    PLASMA: "PLASMA"
};

export const PARTICLE_CONFIG = {
    MAX_PARTICLES: 1000,
    DEFAULT_LIFE: 1.0
};
 
